package com.htyl.park.employee.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * @author weiguang
 */
public class Dict implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.DICT_ID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Long dictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.PID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.NAME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.CODE
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.DESCRIPTION
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.SORT
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.CREATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.UPDATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.CREATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Long createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.UPDATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Long updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.DICT_ID
     *
     * @return the value of sys_dict.DICT_ID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Long getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.DICT_ID
     *
     * @param dictId the value for sys_dict.DICT_ID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setDictId(Long dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.PID
     *
     * @return the value of sys_dict.PID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.PID
     *
     * @param pid the value for sys_dict.PID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.NAME
     *
     * @return the value of sys_dict.NAME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.NAME
     *
     * @param name the value for sys_dict.NAME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.CODE
     *
     * @return the value of sys_dict.CODE
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.CODE
     *
     * @param code the value for sys_dict.CODE
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.DESCRIPTION
     *
     * @return the value of sys_dict.DESCRIPTION
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.DESCRIPTION
     *
     * @param description the value for sys_dict.DESCRIPTION
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.SORT
     *
     * @return the value of sys_dict.SORT
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.SORT
     *
     * @param sort the value for sys_dict.SORT
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.CREATE_TIME
     *
     * @return the value of sys_dict.CREATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.CREATE_TIME
     *
     * @param createTime the value for sys_dict.CREATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.UPDATE_TIME
     *
     * @return the value of sys_dict.UPDATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.UPDATE_TIME
     *
     * @param updateTime the value for sys_dict.UPDATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.CREATE_USER
     *
     * @return the value of sys_dict.CREATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.CREATE_USER
     *
     * @param createUser the value for sys_dict.CREATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.UPDATE_USER
     *
     * @return the value of sys_dict.UPDATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.UPDATE_USER
     *
     * @param updateUser the value for sys_dict.UPDATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }
}