package com.htyl.park.employee.domain;

import java.io.Serializable;
import java.util.Date;

public class Group implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.GROUP_ID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.GROUP_CODE
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String groupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.PARENT_GROUP_ID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Long parentGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.NAME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.DESCRIPTION
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.MONTH_TASK
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Integer monthTask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.CREATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.CREATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Long createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.UPDATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.UPDATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Long updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.GROUP_ID
     *
     * @return the value of sys_group.GROUP_ID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.GROUP_ID
     *
     * @param groupId the value for sys_group.GROUP_ID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.GROUP_CODE
     *
     * @return the value of sys_group.GROUP_CODE
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.GROUP_CODE
     *
     * @param groupCode the value for sys_group.GROUP_CODE
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.PARENT_GROUP_ID
     *
     * @return the value of sys_group.PARENT_GROUP_ID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Long getParentGroupId() {
        return parentGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.PARENT_GROUP_ID
     *
     * @param parentGroupId the value for sys_group.PARENT_GROUP_ID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setParentGroupId(Long parentGroupId) {
        this.parentGroupId = parentGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.NAME
     *
     * @return the value of sys_group.NAME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.NAME
     *
     * @param name the value for sys_group.NAME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.DESCRIPTION
     *
     * @return the value of sys_group.DESCRIPTION
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.DESCRIPTION
     *
     * @param description the value for sys_group.DESCRIPTION
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.MONTH_TASK
     *
     * @return the value of sys_group.MONTH_TASK
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Integer getMonthTask() {
        return monthTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.MONTH_TASK
     *
     * @param monthTask the value for sys_group.MONTH_TASK
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setMonthTask(Integer monthTask) {
        this.monthTask = monthTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.CREATE_TIME
     *
     * @return the value of sys_group.CREATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.CREATE_TIME
     *
     * @param createTime the value for sys_group.CREATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.CREATE_USER
     *
     * @return the value of sys_group.CREATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.CREATE_USER
     *
     * @param createUser the value for sys_group.CREATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.UPDATE_TIME
     *
     * @return the value of sys_group.UPDATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.UPDATE_TIME
     *
     * @param updateTime the value for sys_group.UPDATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.UPDATE_USER
     *
     * @return the value of sys_group.UPDATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.UPDATE_USER
     *
     * @param updateUser the value for sys_group.UPDATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }
}