package com.htyl.park.employee.domain;

import java.io.Serializable;
import java.util.Date;

public class Role implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLE_ID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.PID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.NAME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.DESCRIPTION
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.SORT
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.VERSION
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.CREATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.UPDATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.CREATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Long createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.UPDATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Long updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLE_ID
     *
     * @return the value of sys_role.ROLE_ID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLE_ID
     *
     * @param roleId the value for sys_role.ROLE_ID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.PID
     *
     * @return the value of sys_role.PID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.PID
     *
     * @param pid the value for sys_role.PID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.NAME
     *
     * @return the value of sys_role.NAME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.NAME
     *
     * @param name the value for sys_role.NAME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.DESCRIPTION
     *
     * @return the value of sys_role.DESCRIPTION
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.DESCRIPTION
     *
     * @param description the value for sys_role.DESCRIPTION
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.SORT
     *
     * @return the value of sys_role.SORT
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.SORT
     *
     * @param sort the value for sys_role.SORT
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.VERSION
     *
     * @return the value of sys_role.VERSION
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.VERSION
     *
     * @param version the value for sys_role.VERSION
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.CREATE_TIME
     *
     * @return the value of sys_role.CREATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.CREATE_TIME
     *
     * @param createTime the value for sys_role.CREATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.UPDATE_TIME
     *
     * @return the value of sys_role.UPDATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.UPDATE_TIME
     *
     * @param updateTime the value for sys_role.UPDATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.CREATE_USER
     *
     * @return the value of sys_role.CREATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.CREATE_USER
     *
     * @param createUser the value for sys_role.CREATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.UPDATE_USER
     *
     * @return the value of sys_role.UPDATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.UPDATE_USER
     *
     * @param updateUser the value for sys_role.UPDATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }
}