package com.htyl.park.employee.domain;

import lombok.Data;
import lombok.experimental.Accessors;

import java.io.Serializable;
import java.util.Date;

@Data
@Accessors(chain = true)
public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_ID
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.AVATAR
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ACCOUNT
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PASSWORD
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.SALT
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.NAME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.BIRTHDAY
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.EMPLOYEE_NUMBER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String employeeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ADDRESS
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.SEX
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.EMAIL
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PHONE
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.STATUS
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CREATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CREATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Long createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.UPDATE_TIME
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.UPDATE_USER
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Long updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.VERSION
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ENTRY_DATE
     *
     * @mbg.generated Wed Nov 20 12:02:38 CST 2019
     */
    private Date entryDate;
}