package com.htyl.park.employee.mapper;

import com.htyl.park.employee.domain.Group;
import com.htyl.park.employee.domain.GroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbg.generated Fri Nov 15 14:13:10 CST 2019
     */
    long countByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbg.generated Fri Nov 15 14:13:10 CST 2019
     */
    int deleteByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbg.generated Fri Nov 15 14:13:10 CST 2019
     */
    int deleteByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbg.generated Fri Nov 15 14:13:10 CST 2019
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbg.generated Fri Nov 15 14:13:10 CST 2019
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbg.generated Fri Nov 15 14:13:10 CST 2019
     */
    List<Group> selectByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbg.generated Fri Nov 15 14:13:10 CST 2019
     */
    Group selectByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbg.generated Fri Nov 15 14:13:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Group record, @Param("example") GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbg.generated Fri Nov 15 14:13:10 CST 2019
     */
    int updateByExample(@Param("record") Group record, @Param("example") GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbg.generated Fri Nov 15 14:13:10 CST 2019
     */
    int updateByPrimaryKeySelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbg.generated Fri Nov 15 14:13:10 CST 2019
     */
    int updateByPrimaryKey(Group record);

    /**
     *  建立用户与分组的关系
     * @param groupId
     * @param userIds
     * @return
     */
    int insertGroupUser(@Param("groupId")Long groupId,@Param("userIds")List<Long> userIds);

    /**
     *  删除分组与用户的关联关系
     * @param groupId
     * @return
     */
    int deleteGroupUser(@Param("groupId")Long groupId);
}