#nacos:
#  discovery:
#    server-addr: 127.0.0.1:8848
#  config:
#    server-addr: 127.0.0.1:8848
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/park_user
    username: nacos
    password: nacos
nacos:
  discovery:
    server-addr: nacos://127.0.0.1:8848
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  application:
    name: provider_employee